# Generated by Django 2.2.3 on 2019-07-16 12:04

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('isValidated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('AID', 'AID'), ('ALPIN', 'ALPIN'), ('BIGWALL', 'BIGWALL'), ('BOULDER', 'BOULDER'), ('DWS', 'DWS'), ('MULTIPITCH', 'MULTIPITCH'), ('SPORT', 'SPORT')], max_length=255)),
                ('openIn', models.DateField()),
                ('faIn', models.DateField()),
                ('description', models.CharField(max_length=5000)),
                ('isValidated', models.BooleanField(default=False)),
                ('crag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crags.Crag')),
            ],
        ),
        migrations.CreateModel(
            name='NameStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.TextField()),
                ('source', models.CharField(max_length=500)),
                ('isValidated', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crags.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Anecdote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anecdote', models.TextField()),
                ('source', models.CharField(max_length=500)),
                ('isValidated', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crags.Route')),
            ],
        ),
    ]
