# Generated by Django 2.2.3 on 2019-07-11 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.CharField(max_length=5000)),
                ('source', models.CharField(max_length=500)),
                ('isValidated', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crags.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Anecdote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anecdote', models.CharField(max_length=5000)),
                ('source', models.CharField(max_length=500)),
                ('isValidated', models.BooleanField(default=False)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crags.Route')),
            ],
        ),
    ]
